### ISSUE TITLE
Alow user to specify music service.

### ISSUE THREAD

**Issue by emceeaich** [mozilla/firefox-voice#940] opened 2020-02-04 20:23 UTC

**Comment by awallin** [comment] 2020-02-04 20:34
@emceeaich Thanks for the feedback. We certainly have this feature in mind. Initially it will likely require enabling each service individually. Do you have a preferred music service you want to see implemented?

How do you envision setting/configuring the service? Once set do you envision asking to play a song or artists ("play green day") would also use the preferred music service?

Related to #931 #302 #303 #304

**Comment by ianb** [comment] 2020-02-05 22:12
Closing it as a duplicate of the other services tickets. Though if there's a specific intent or phrase that you had in mind, please open this and indicate what you tried and what you wanted.

**Closed by ianb** 2020-02-05 22:12 UTC
