### ISSUE TITLE
"Unmute page" opens a new tab for Chrome 64: How to Mute and Unmute Sites

### ISSUE THREAD

**Issue by Simpcyclassy** [mozilla/firefox-voice#1253] opened 2020-03-12 14:30 UTC
**Prerequisites**:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed. (if applicable)
A playing Youtube tab is made active.

**STR**:
Manually mute the Youtube page from the tab.
Use the shortcut or click on the mic icon from the browser toolbar.
Write the "Unmute page" command.

**Expected result:**
The page/tab is unmuted.

**Actual result**:
A new [tab](https://techdows.com/2017/11/mute-and-unmute-sites-in-chrome-63.html) opens

**Notes**:
Reproduced on MacOS Catalina 10.15.3 with Firefox Nightly 76.0a1 (2020-03-12).

**Comment by alexandra-martin** [comment] 2020-03-12 14:58
Tested on Mac 10.15 and 10.15.03 with Firefox Nightly 76.0a1 (2020-03-12) and I couldn't reproduce.
It may be location depended.

**Comment by ianb** [comment] 2020-05-20 19:54
Duplicate of  #1251

**Closed by ianb** 2020-05-20 19:54 UTC
