### ISSUE TITLE
"Play Green Day" displays "No results found for Green Day" in doorhanger 

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1337] opened 2020-03-19 13:52 UTC
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
Make sure that no account is logged in on Spotify.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the Spotify "Play" command, e.g. "Play Green Day".

### Expected result:
Spotify opens in a new tab and the user is advised to log in to listen to music.

### Actual result:
The "No results found for Green Day" text is displayed in the doorhanger.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-19).
If "Play Green Day" command is made a second time, "Start listening with a free Spotify account" is displayed, to advise the user to log in to listen to music.
For some "Play" commands, the issue is not reproduced. (e.g. "Play Muse") (2nd gif)
If an account is logged in, the issue is not reproducing.

![1](https://user-images.githubusercontent.com/54401091/77073941-b6ecce80-69f8-11ea-863f-50116892297b.gif)

![3](https://user-images.githubusercontent.com/54401091/77074101-f9161000-69f8-11ea-9ded-9181c6f7a93c.gif)

**Comment by alexandra-martin** [comment] 2020-03-19 14:40
The issue can be sometimes reproduced also if a Spotify account is logged in.

![9](https://user-images.githubusercontent.com/54401091/77079161-4184fc00-6a00-11ea-9095-2a858cb82d48.gif)

**Comment by annlinros** [comment] 2020-03-21 13:24
Hi @alexandra-martin 

I tried to reproduce the bug on MacOS 10.14.6 with Firefox Nightly 76.0a1.
I got the expected results.
When I wasn't logged in, I got a prompt to log in to spotify on a new tab.
If I were already logged in, I got greena day results on a new spotify tab..

Is the bug fixed now ?

**Comment by GangaChatrvedi** [comment] 2020-03-22 07:35
@annlinros while working on issue #1339 I accidentally reproduced this issue. Since then I have reproduced it so many times with the same steps @alexandra-martin mentioned.

@ianb I would like to work on this.

**Closed** 2020-07-09 19:17 UTC
Labels: bug
