### ISSUE TITLE
Blank "Doorhanger" space disappears after pressing "Enter" for search result with less description

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#267] opened 2019-09-18 06:50 UTC
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Say a "Search" command, e.g. "Search fox" or "Search box" and wait for the result to be displayed.
3. Press "Enter".

### Expected result:
"Doorhanger" doesn't have display issues.

### Actual result:
For a search result with less description the "Doorhanger" will have a blank area at the bottom, which will disappear after the first pressed "Enter" key.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
Clicking inside the "Doorhanger" first will not let the blank area to disappear after pressing "Enter" like in [156](https://github.com/mozilla/firefox-voice/issues/156).

![32](https://user-images.githubusercontent.com/54401091/65122246-20176900-d9f9-11e9-95ad-45c9ef0a5e2d.gif)

**Comment by ianb** [comment] 2019-09-18 20:20
I'm guessing Enter triggers Firefox to recalculate the size of the popup. Maybe there's another way to trigger that resize?

**Comment by alexandra-martin** [comment] 2019-09-30 11:12
Update: After pressing "Enter", the blank space will not disappear anymore. The question now is, should the blank space be there or should the "Doorhanger" size be recalculated in some way, if such blank spaces occur?

![79](https://user-images.githubusercontent.com/54401091/65872808-1f33ef00-e38a-11e9-9a11-7b320d4052f4.gif)

**Comment by vandnakapoor19** [comment] 2020-03-06 16:42
I'm Outreachy 2020 Applicant and want to solve the issue.
Thanks

**Comment by tonynguyen111997** [comment] 2020-03-06 17:06
Hi, I am also interested in tackling this issue if @vandnakapoor19 decides to not take it. Thank you.

**Comment by ianb** [comment] 2020-03-06 17:45
@vandnakapoor19 Please be sure to re-verify the problem, there's a chance this was fixed somewhere along the way. (And if it was fixed, please follow up so we can close this, thanks!)

**Comment by vandnakapoor19** [comment] 2020-03-06 17:59
Thanks! Let me recheck this and I'll let you know.

**Comment by vandnakapoor19** [comment] 2020-03-09 12:54
@ianb I’m not able to reproduce the above issue & some additional observations are as follows.
•	“Search” command display results in a new tab.
•	Doorhanger result is available only for the “featured snippet” response.

System Configuration: -
OS: Windows 10x64
Firefox Nightly: Version 75.0a1
Node: v12.16.1

![result_weather](https://user-images.githubusercontent.com/45131874/76184493-860fcc80-61a2-11ea-9133-bfc526322604.gif)
![voice_search_final](https://user-images.githubusercontent.com/45131874/76184866-e9e6c500-61a3-11ea-96ff-00fc0499b5aa.gif)

**Comment by ianb** [comment] 2020-03-09 17:04
Thanks for verifying this @vandnakapoor19, I believe the search behavior you're seeing is correct and this particular bug is no longer reproducible.

**Closed by ianb** 2020-03-09 17:04 UTC
Labels: bug, good first issue
