### ISSUE TITLE
"Read this page" command doesn't work properly

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#974] opened 2020-02-07 18:21 UTC
If you say "Read this page" in a webpage which is abled to Read mode, it returns the below error after loaded the Reading page
![immagine](https://user-images.githubusercontent.com/32335378/74054779-f0382480-49de-11ea-9c91-7f90db4ee1b0.png)

**Comment by ianb** [comment] 2020-02-19 22:28
Duplicate of #706

**Closed by ianb** 2020-02-19 22:28 UTC
Labels: duplicate
