### ISSUE TITLE
A new “Welcome to Firefox Voice” tab opens after clicking “How Mozilla ensures voice privacy” link from the “Doorhanger”

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#164] opened 2019-09-02 14:30 UTC
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Click on the mic icon from the browser toolbar.
2. Click on the “How Mozilla ensures voice privacy” link from the bottom of the “Doorhanger”.

### Expected result:
A page with voice privacy information is displayed.

### Actual result:
A new “Doorhanger” without the “Zap” animation opens and a new “Welcome to Firefox Voice” tab opens.

### Notes:
Reproduced on Mac 10.14.6 with Firefox Nightly 70.0a1 (64-bit).

![voice 1](https://user-images.githubusercontent.com/54401091/64121325-2a095d00-cda7-11e9-9e2b-07b3a46fcfc8.gif)

**Comment by ianb** [comment] 2019-09-03 17:22
Duplicate of #89

**Closed by ianb** 2019-09-03 17:22 UTC
Labels: bug
