### ISSUE TITLE
Customisable wakeword

### ISSUE THREAD

**Issue by Sav22999** [mozilla/firefox-voice#1217] opened 2020-03-10 20:19 UTC
I think that could be a good idea can choose a customisable wakeword, in addition to the list.
Just add a "textbox" and there you can write your wakeword.

**Comment by Akanksha1212** [comment] 2020-03-10 20:48
Hi, I would like to work on this.

**Comment by awallin** [comment] 2020-04-27 17:14
Closing this as it's a duplicate of this wakeword implementation.
https://github.com/mozilla/firefox-voice/issues/1037

**Closed by awallin** 2020-04-27 17:14 UTC
