### ISSUE TITLE
Search results on Spotify are not displayed when the same two "Play" commands are made

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#377] opened 2019-10-07 13:17 UTC
### Prerequisites:
Mic permissions are enabled.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write a "Play" command, e.g. "Play Green Day".
3. After the Spotify tab is successfully playing repeat steps 1 and 2 from either the Spotify tab or another opened tab.

### Expected result:
The Spotify tab doesn't have display issues.

### Actual result:
The search results for Green Day previously displayed are not longer visible in the Spotify tab. 

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 71.0a1 (64-bit).
If the "Play" commands are different the search results will display the requested artist/songs.
The bug is reproduced both when the Spotify tab plays or is paused. 
On Mac there is an "Internal error: Error: Timeout waiting for .tracklist-play-pause, .top-artist .cover-art-playback" error message displayed in the "Doorhanger".

![105](https://user-images.githubusercontent.com/54401091/66314905-6dfaff00-e91d-11e9-87fc-d465a75c3228.gif)

 ![108](https://user-images.githubusercontent.com/54401091/66314307-81599a80-e91c-11e9-9bbe-a664bd2914ea.gif)

<img width="1280" alt="Screenshot 2019-10-07 at 13 37 55" src="https://user-images.githubusercontent.com/54401091/66314375-9d5d3c00-e91c-11e9-907b-8fb4a623d993.png">

**Comment by ianb** [comment] 2019-10-10 16:34
Duplicate of #345

**Closed by ianb** 2019-10-10 16:34 UTC
Labels: bug
